# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5a2f66a30953c9fc6e05803d2024f376412ffb067988c0fa4b1b7cbbb7477639982148bc3af57202326e8555cd2427166218fb979463c768a267cd33b998360

test:
  secret_key_base: 3006f376d09dcfd133b41b6db2c8b69ba4fd7ed8e5b247431c9741715b887729d2f86f5209e335d174a793539e2152be3c7ff24b9c8c9950703a8a530654d2e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
